### ISSUE TITLE
Data files

### ISSUE THREAD

**Issue by ZeWang95** [batra-mlp-lab/avsd#2]
Hi, thanks for your great works.

May I ask if it possible to share the data files (all the h5 files and json files)?
The instructions on the data preparation is so unclear.

Thanks you very much.

**Comment by hudaAlamri** [comment]
Hi, 

The extracted features can be found here https://drive.google.com/drive/folders/14zlHmNFkCgptiGttwWKrsaaz5vVUFs00?usp=sharing

**Comment by ZeWang95** [comment]
Thank you so much for sharing the files!!!
And thanks again for your great work!

**Comment by patrick-tssn** [comment]
hi,
Is there any way to get the test set?
thx a lot!
